### ISSUE TITLE
Ability to pass in cookies file via argument

### ISSUE THREAD

**Issue by vil33** [mrwnwttk/youtube_stream_capture#1]
Would it be possible to add a similar feature to how you're able to pass in the cookies file via the --cookies argument like in youtube-dl? This would make it must easier when cookies expire or need to be renewed.

**Comment by mrwnwttk** [comment]
Definitely possible, but I'd prefer to just put them in a json file. those cookie strings google chrome gives out are incredibly long, at least on youtube. How does that sound?

**Comment by vil33** [comment]
That sounds good. Usually I just grab the cookie from youtube with something like https://addons.mozilla.org/en-CA/firefox/addon/cookies-txt/ and pass it in to youtube-dl. JSON would work with this method too I'm guessing.

**Comment by mrwnwttk** [comment]
@vil33 
Finally got around to implementing this. More details can be found in the README, let me know if this works for you.

**Comment by mrwnwttk** [comment]
Alright it's been three weeks without a response. I'll consider this one solved.
