### ISSUE TITLE
Hangs after creating directory

### ISSUE THREAD

**Issue by AndrewGoulding** [mrwnwttk/youtube_stream_capture#12]
The program hangs after creating directory for the segments. I use the following command:

`.\youtube_stream_capture.py python https://www.youtube.com/watch?v=6rPinHZTm3g --output_directory D:\temp`

And the program does the following without doing anything else:

'[INFO] Created directory D:\youtube_stream_capture\segments_6rPinHZTm3g'

I am unsure what I am doing wrong.

**Comment by AndrewGoulding** [comment]
So I realized I was using --output_directory instead of --output-directory, so the program is now correctly assigning the output directory, however The program is still doing nothing after this.

**Comment by glubsy** [comment]
You are not invoking the program correctly. It should probably something like: 

`python ./youtube_stream_capture.py  --output_directory "D:\temp" "https://www.youtube.com/watch?v=6rPinHZTm3g"`

Although I'm not sure because Microsoft Windows is weird.

**Comment by mrwnwttk** [comment]
Running the program the intended way as @glubsy said would certainly help (Powershell wants to see backslashes but you can usually get yourself to where you wanna be by just tabbing through the files in the folder).

Did you set up aria2c correctly? The script itself is still working just fine for me, even without a cookie.
