### ISSUE TITLE
Add licence, configurable output directory

### ISSUE THREAD

**Issue by axcore** [mrwnwttk/youtube_stream_capture#2]
Hi @mrwnwttk, I have been adding support for YTSC in my [GUI](https://github.com/), but I have run into the following insurmountable problems:

1. YTSC appears to store segments in whatever the current directory is, which in this case is in the directory where all the GUI source code is. Could you please add some way to specify the directory for YTSC to use, perhaps

`python3 youtube_stream_capture.py [Link to the livestream] [optional: start segment] [optional: output directory]`

2. I could make the changes myself, but you haven't decided yet which licence applies to YTSC. At the moment I don't think I can even fork the YTSC repository for testing purposes. So: could you please make a decision about that :+1: 

The other problems are not insurmountable, but would be nice:

3. Is there any way for the two merge scripts to report, whether they were successful or not? If the first script produces a file seemingly thousands of hours in length, I can run the second one. But at the moment I don't know if the first script is producing a faulty video, or not.

4. At the moment, I have to guess the path to the final output file (specifically, I don't know the file extension). This is fine, but not very elegant. Could the merge scripts `print` the path to their output file, so that I don't have to guess?

(I have added 1 issue rather than 4 separate ones, to avoid splitting up the conversations.)

**Comment by mrwnwttk** [comment]
Thanks for reaching out, I'll implement all of those points over the next couple of days probably. Detecting the proper output of the two merge scrips shouldn't be too difficult, though it would mean having a couple seconds more runtime for the merge script. Shouldn't be too big of an issue though.

**Comment by mrwnwttk** [comment]
@axcore Added all the features you requested. The merge script is now a single script that can automatically detect which one of the two files is broken. Here's a sample output (though it's missing the fancy colors here on GitHub):

```
$ python3 merge.py https://www.youtube.com/watch?v=wSYFfVrCipA --output-directory /mnt/c/Users/X1C4/Desktop/
[INFO] Set output directory to /mnt/c/Users/X1C4/Desktop
[INFO] Checking available segments...
[INFO] First segment: /mnt/c/Users/X1C4/Desktop/0_wSYFfVrCipA_audio.ts
[INFO] Last segment: /mnt/c/Users/X1C4/Desktop/1646_wSYFfVrCipA_video.ts
[INFO] Total number of segments (audio & video): 3294
[INFO] Checking for missing segments...
[INFO] No missing segments!
[INFO] Analyzing files...
[INFO] codec_name=h264
[INFO] codec_tag_string=avc1
[INFO] height=1080
[INFO] coded_height=1088
[INFO] r_frame_rate=30/1
[INFO] Testing merge method 1 / 2...
[INFO] Testing merge method 2 / 2...
[INFO] Checking file of method 1...
[INFO] duration=500.014000
[INFO] Checking file of method 2...
[INFO] duration=5.522086
[WARNING] File of method 2 broken.
[INFO] Using method 1 for this livestream. This process might take a while...
Output file: /mnt/c/Users/X1C4/Desktop/wSYFfVrCipA.mp4
```
The last line contains the absolute path for the final file. Parsing that should be trivial.

Both the merge script and the recording script now have an optional `--output-directory` argument, which takes either absolute or relative paths. I've tested this on both Windows as well as Linux (WSL). colorama is a new necessary module, but it's included in `requirements.txt`.

Let me know if you run into any issues.

**Comment by axcore** [comment]
Oh, that's great, thanks a lot!

I have tested the updated, and run into this problem: the segments sub-directory is still created in the current directory, even when a location for the output file is specified. For example:

![tartube-test](https://user-images.githubusercontent.com/37951926/100343631-87568300-2fd7-11eb-81f9-9437b15e3f2b.png)

This is potentially disastrous, because (for example) a debian package would be using a current directory that is read-only.

When an output file is specified, could the segments directory be at the same location? In other words

```
/my/favourite/directory/youtube_stream_capture.py
/my/favourite/directory/output_video_file.mp4
/my/favourite/directory/segments_ABCDEFGH/0_ABCDEFGH_video.ts
```

**Comment by mrwnwttk** [comment]
You didn't specify the --output-directory option, that's why it defaulted to the current directory.

**Comment by axcore** [comment]
Oops! Ok, I'll test it again, this time paying attention...

**Comment by axcore** [comment]
Everything works fine, and the new code with YTSC has been [uploaded](https://github.com/axcore/tartube). Thanks for your help!
