### ISSUE TITLE
Status: 200 - Nothing downloads

### ISSUE THREAD

**Issue by Linden10** [mrwnwttk/youtube_stream_capture#3]
Hello, it's me again! I've been using your script and it worked pretty well the first time I used it!

However just recently (two days ago) I've been having issues downloading livestreams off youtube, tested on multiple streams
with the same result!

Every time I use the script now, I get a "status 200" message, never progressing further beyond repeating the same message.
I even tested it with a cookies file, using the google chrome extension "get cookies.txt" which converts the cookies of the current tab you're on into a cookies.txt file!

The same thing happens with and without the cookies file, status 200 as seen in my command below:
`PS C:\Users\ASUS\Downloads\youtube_stream_capture-main> python .\youtube_stream_capture.py https://www.youtube.com/watch?v=dVpSy1JCJbk
[INFO] Created directory C:\Users\ASUS\Downloads\youtube_stream_capture-main\segments_dVpSy1JCJbk
Status code: 200`

I have no idea what's causing it!

**Comment by mrwnwttk** [comment]
Hey! Sorry I didn't actually try the script out again before commenting on that gist thread. YouTube changed something about the position and layout of their embedded JSON. I just pushed an update that resolves this. Took like three minutes, but I should've taken a look two days ago :D

**Comment by Linden10** [comment]
Ah I see! I'll try it out, thank you!
Hopefully everything works out great again!

**Comment by Ichunjo** [comment]
Hello, looks like the same issue happens again. Using a cookie file seems to fix it though it takes a bit of time

**Comment by glubsy** [comment]
This might be due to Youtube now defaulting to showing this (stupid) consent page if they don't see a cookie showing that you have already agreed to being tracked by cookies. 

You can see that youtube-dl implemented a fix there: https://github.com/ytdl-org/youtube-dl/commit/14f29f087e6097feb46bdb84878924bc410a57eb

I have integrated this fix in my ["livestream saver" script](https://github.com/glubsy/livestream_saver).

**Comment by Ichunjo** [comment]
Awesome, thanks a lot. Your Livestream Saver is exactly what I need
