### ISSUE TITLE
Merge script fails after download successful

### ISSUE THREAD

**Issue by glubsy** [mrwnwttk/youtube_stream_capture#4]
The script seems to work, however once the stream has ended, it doesn't stop downloading on its own. Had to send keyboard interrupt more than twice for it to finally abort. Not sure if that corrupted anything, despite the errors displayed (doesn't seem to, all available files where already successfully downloaded anyway). 
```
$> ./merge.py  https://www.youtube.com/watch\?v\=m-Bq5CG_rGQ 
[INFO] Checking available segments...
[INFO] First segment: /youtube_stream_capture/0_m-Bq5CG_rGQ_audio.ts
[INFO] Last segment: /youtube_stream_capture/4872_m-Bq5CG_rGQ_video.ts
[INFO] Total number of segments (audio & video): 9746
[INFO] Checking for missing segments...
[INFO] No missing segments!
[INFO] Analyzing files...
[INFO] codec_name=h264
[INFO] codec_tag_string=avc1
[INFO] height=1080
[INFO] coded_height=1088
[INFO] r_frame_rate=60/1
[INFO] Testing merge method 1 / 2...
[INFO] Testing merge method 2 / 2...
[INFO] Checking file of method 1...
[INFO] duration=4950.999667
[INFO] Checking file of method 2...
[INFO] duration=99.999667
[WARNING] File of method 1 broken.
[WARNING] File of method 2 broken.
[ERROR] Both methods aren't working for some reason. Don't delete the recording just yet! If you're sure that you didn't mess with the files in any way, please open an issue on Github and report this.
```
Not sure what to look for right now. Note: this is a DASH stream.
On the other hand youtube-dlc managed to download and remux the same stream just fine with `--hls-use-mpegts` flag.

Side note: the `time.sleep(1)` statements slow down the download of chunks so much that it lags behind the actual stream position a lot. Fortunately Youtube keeps those in cache for a little while after the stream has ended, but I wouldn't count on that too much, so perhaps removing the `sleep(1)` would be better?

**Comment by mrwnwttk** [comment]
> The script seems to work, however, once the stream has ended, it doesn't stop downloading on its own. 

If by the end of the stream there are still segments left, then it will keep on downloading. It takes a minute or two after the stream has finished preventing the recording from stopping in case a stream just accidentally crashes (or at least that's what it's supposed to). It should loop over the last couple segments for a while and then close on its own.

> so perhaps removing the sleep(1) would be better?

I've commented it out for the time being.

> Not sure what to look for right now. Note: this is a DASH stream.
> On the other hand youtube-dlc managed to download and remux the same stream just fine with --hls-use-mpegts flag.

The merge script determines whether each method is broken based on the duration of the segments. I have yet to find out what exactly causes the variation in length, but up until this point, all I had come across were segments with lengths between two and ten seconds. Now this stream comes along with segments that amount to just barely under one second in length, which obviously doesn't work with the line `if duration_v1 < (len(merge_v1_test_segments_audio)) or (duration_v1 > 20 * len(merge_v1_test_segments_audio))`. I've adjusted it accordingly to allow for segments of about one second in length.

Let me know if this works for you.

**Comment by glubsy** [comment]
Awesome, that fixed the problem. Thank you!

**Comment by glubsy** [comment]
Commenting out the sleep instructions seem to work just fine still.

**Comment by mrwnwttk** [comment]
In that case, I'll just leave things the way they are at the moment, no need to revert the commit.
