### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by beta2k** [mrwnwttk/youtube_stream_capture#7]
I am trying to download live stream that started 8.5 hours ago. I run into a timeout, but don't know why?

![image](https://user-images.githubusercontent.com/1133118/112347909-96201e80-8cc7-11eb-8334-1d6819821209.png)

**Comment by mrwnwttk** [comment]
Are you sure you have aria2 installed and set up correctly? Because it should be showing up  here...

**Comment by mrwnwttk** [comment]
Just tried the link you showed in the screenshot and it's rushing through the recording, so everything is working on YouTube's end the way it's supposed to.

**Comment by beta2k** [comment]
Oh okay. I just installed aria2c. so maybe that's my issue?

**Comment by mrwnwttk** [comment]
Try again. If aria2 is installed and shows up when you type `aria2` in the terminal then everything should work.

**Comment by beta2k** [comment]
It didnt. But I just googled and it seems that `aria2c` and `aria2` can be used interchangably? So I just renamed `aria2c` to `aria`, but still not working. it takes very long to parse the URL and then nothing happens until the error. do you have discord or telegram?

**Comment by beta2k** [comment]
can you show me a screenshto of the first few seconds into the stream? i want to know if the "real start" of the video is caught by this downloader.

**Comment by beta2k** [comment]
works now. had to rename aria2c.exe into aria2.exe and put in the same folder as the python.
thanks!

**Comment by mrwnwttk** [comment]
Glad you were able to resolve it!
